### ISSUE TITLE
Add comments section to Intro to Python

### ISSUE THREAD

**Issue by clairecahoon** [NCSU-Libraries/data-viz-workshops#11]
I'm sure you talk about it when going through the materials, but for beginners and/or people who return to the workshop materials later, it might be helpful to have a section explain what comments are. I wrote a draft here, it could go after the "Jupyter Notebooks and Google Colaboratory" section:

## Using Comments

In the code below, you'll see some sections that start with # and are shown in green font. These are **comments**, which are ways to annotate your code even outside of Google Colabs.
Python skips over comments when running code, so those lines don't execute any instructions. They can be helpful when debugging code, and for making notes in plain language to help you make sense of the code.

**Comment by csbailey5t** [comment]
Fixed in 6debcbf99c71cbe6231a5b27481cc529b847201e
