### ISSUE TITLE
Add download instructions to Intro to Python resources

### ISSUE THREAD

**Issue by clairecahoon** [NCSU-Libraries/data-viz-workshops#12]
We could add downloading Python for your own computer to resources, with a note to see us if they need more specific help (since they wouldn't need it for the workshop, this would be more of an FYI). If there's an IDE we recommend, or if we want to emphasize Colabs again, that could also be part of this. 
Draft:

See the [official Python site's download page](https://www.python.org/downloads/) to download Python on your own computer. If you need help with this process or with using an IDE (Integrated Development Environment), contact us at Data & Visualization Services.

**Comment by csbailey5t** [comment]
Fixed in 6debcbf99c71cbe6231a5b27481cc529b847201e

I put in section with some options for install and a brief separate recommendation of VS Code as an editor.
