### ISSUE TITLE
Axis Swap?

### ISSUE THREAD

**Issue by clairecahoon** [NCSU-Libraries/data-viz-workshops#14]
In the bar chart example where a title and axis labels are added (just after the text "For example, we could set axis labels or a title."), the axes are switched. The y-axis shows races, and is labeled "Number of drivers" and vice versa for the x axis. Is this intentional?

**Comment by csbailey5t** [comment]
@clairecahoon this is not intentional. Thanks for catching.

**Comment by csbailey5t** [comment]
Fixed in da0f2cb747f6871b17c927f56fd209c5f86b5cbb
